// <auto-generated />
using System;
using Hochtief.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hochtief.Migrations
{
    [DbContext(typeof(TestDBContext))]
    partial class TestDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hochtief.Models.DefinitionPDSLevel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("pds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdsName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("definitionPDSLevels");
                });

            modelBuilder.Entity("Hochtief.Models.MainActivity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("activityInternExtern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("activity_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("activitytype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("activitytypedetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("formversion")
                        .HasColumnType("int");

                    b.Property<string>("hours_activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("itemno")
                        .HasColumnType("int");

                    b.Property<string>("kolonnenae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pds01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pds02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pds03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pds04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pds05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pds06")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rowid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("MainActivities");
                });

            modelBuilder.Entity("Hochtief.Models.MainActivitySubTasks", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("activitySubTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("formversion")
                        .HasColumnType("int");

                    b.Property<int>("itemno")
                        .HasColumnType("int");

                    b.Property<int>("rowid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("mainActivitySubTasks");
                });

            modelBuilder.Entity("Hochtief.Models.MainAdditionalWorks", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("additionalWorksActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("additionalWorksPds04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("additionalWorksPds05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("additionalWorksPds06")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("additionalWorksTxt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("eventCategory")
                        .HasColumnType("int");

                    b.Property<string>("eventHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("itemno")
                        .HasColumnType("int");

                    b.Property<string>("pds01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pds02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rowid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("mainAdditionalWorks");
                });

            modelBuilder.Entity("Hochtief.Models.MainEquipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("activity")
                        .HasColumnType("float");

                    b.Property<string>("equipment01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment01Contractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("equipment01Hours")
                        .HasColumnType("float");

                    b.Property<double>("equipment01Num")
                        .HasColumnType("float");

                    b.Property<string>("equipment02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment02Contractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment02Hours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment02Num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment03Contractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment03Hours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment03Num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment04Contractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment04Hours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment04Num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment05Contractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment05Hours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment05Num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment06")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment06Contractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment06Hours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("equipment06Num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("formversion")
                        .HasColumnType("int");

                    b.Property<int>("itemno")
                        .HasColumnType("int");

                    b.Property<int>("rowid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("MainEquipment");
                });

            modelBuilder.Entity("Hochtief.Models.MainField2BIM", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ReportBreakTimeNumeric")
                        .HasColumnType("float");

                    b.Property<string>("ReportDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportEndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportHours")
                        .HasColumnType("int");

                    b.Property<string>("ReportStartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TempTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeHours")
                        .HasColumnType("int");

                    b.Property<string>("completetime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("formversion")
                        .HasColumnType("int");

                    b.Property<string>("headerPds01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("headerPds02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("headerPds03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("headerPds04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("itemno")
                        .HasColumnType("int");

                    b.Property<double>("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.Property<string>("pds01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pds01Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectDef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reportID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("starttime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timeRang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userfirstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userlastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("mainField2BIMs");
                });

            modelBuilder.Entity("Hochtief.Models.MainGeneral", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FreigabeAutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreigabeDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreigabeDate1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ReportBreakTimeNum")
                        .HasColumnType("float");

                    b.Property<string>("ReportDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportEndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ReportHours")
                        .HasColumnType("float");

                    b.Property<string>("ReportStartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bautagebuchAutoPolier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("formversion")
                        .HasColumnType("int");

                    b.Property<string>("genehmigungAutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("itemno")
                        .HasColumnType("int");

                    b.Property<string>("reportID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rowid")
                        .HasColumnType("int");

                    b.Property<string>("taskname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usemail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("mainGenerals");
                });

            modelBuilder.Entity("Hochtief.Models.MainPhotos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("fotosActivitySelection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("itemno")
                        .HasColumnType("int");

                    b.Property<string>("reportID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("taskname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("mainPhotos");
                });

            modelBuilder.Entity("Hochtief.Models.MainSignaturePhotos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.Property<string>("SignaturePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("mainSignaturePhotos");
                });

            modelBuilder.Entity("Hochtief.Models.Pds", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocL3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdsL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdsL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdsL3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdsL4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdsL5")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("pds");
                });

            modelBuilder.Entity("Hochtief.Models.Schedule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bautagesbericht")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullDescr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDTask")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocL3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdsID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskOriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pds02Descr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdsL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdsL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdsL3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdsL4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdsL5")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("Hochtief.Models.SourceCompany", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("De_firma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("En_company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pds01")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("sourceCompanies");
                });

            modelBuilder.Entity("Hochtief.Models.SourceRole", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("De_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("En_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Source_Roles");
                });

            modelBuilder.Entity("Hochtief.Models.TestTabelle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fullname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("testTabelle");
                });

            modelBuilder.Entity("Hochtief.Models.Weather", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("datum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temp_condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temp_time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
