// <auto-generated />
using Hochtief.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hochtief.Migrations
{
    [DbContext(typeof(TestDBContext))]
    partial class TestDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hochtief.Models.LabourInternal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("formversion")
                        .HasColumnType("int");

                    b.Property<double>("hoursActivity")
                        .HasColumnType("float");

                    b.Property<int>("itemno")
                        .HasColumnType("int");

                    b.Property<string>("posht")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rowid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("LabourInt");
                });

            modelBuilder.Entity("Hochtief.Models.SourceCompany", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("De_firma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("En_company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pds01")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("sourceCompanies");
                });

            modelBuilder.Entity("Hochtief.Models.SourceEquipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("De_equipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("En_equipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code_Company")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("sourceEquipment");
                });

            modelBuilder.Entity("Hochtief.Models.SourceRole", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("De_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("En_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Source_Roles");
                });

            modelBuilder.Entity("Hochtief.Models.TestTabelle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fullname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("testTabelle");
                });

            modelBuilder.Entity("Hochtief.Models.Weather", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("datum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temp_condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temp_time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
