//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDBSourceCompany
    {
        public int SourceCompany_id { get; set; }
        public string En_Company { get; set; }
        public string De_Frima { get; set; }
        public string Code { get; set; }
        public string Pds01 { get; set; }
    }
}
