//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserReg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UserTab
    {
        public int UserID { get; set;}
        [Required(ErrorMessage ="This field is required please! ")]
        public string Username { get; set;}
        [Required(ErrorMessage = "This field is required please! ")]
        [DataType(DataType.Password)]
        public string Password { get; set;}
        [DataType(DataType.Password)]
        [DisplayName("Confirm Password")]
        [Compare("Password")]
        public string ConfirmPassword { get; set;}
        public Nullable<bool> isAdmin { get; set;}
    }
}
