//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class A40Entities : DbContext
    {
        public A40Entities()
            : base("name=A40Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A40Labour> A40Labour { get; set; }
        public virtual DbSet<A40SourceCompany> A40SourceCompany { get; set; }
        public virtual DbSet<A40SourceEquipment> A40SourceEquipment { get; set; }
        public virtual DbSet<A40SourceRole> A40SourceRole { get; set; }
    }
}
