//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICEEntities : DbContext
    {
        public ICEEntities()
            : base("name=ICEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ICELabour> ICELabour { get; set; }
        public virtual DbSet<ICESourceCompany> ICESourceCompany { get; set; }
        public virtual DbSet<ICESourceEquipment> ICESourceEquipment { get; set; }
        public virtual DbSet<ICESourceRole> ICESourceRole { get; set; }
    }
}
