//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MohamedAzloukSandboxEntitiesA6 : DbContext
    {
        public MohamedAzloukSandboxEntitiesA6()
            : base("name=MohamedAzloukSandboxEntitiesA6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A6Labourtest> A6Labourtest { get; set; }
        public virtual DbSet<A6SourceCompanytest> A6SourceCompanytest { get; set; }
        public virtual DbSet<A6SourceEquipmenttest> A6SourceEquipmenttest { get; set; }
        public virtual DbSet<A6SourceRoletest> A6SourceRoletest { get; set; }
    }
}
