//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MohamedAzloukSandboxEntities10 : DbContext
    {
        public MohamedAzloukSandboxEntities10()
            : base("name=MohamedAzloukSandboxEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<U3Labour> U3Labour { get; set; }
        public virtual DbSet<U3SourceCompany> U3SourceCompany { get; set; }
        public virtual DbSet<U3SourceEquipment> U3SourceEquipment { get; set; }
        public virtual DbSet<U3SourceRole> U3SourceRole { get; set; }
    }
}
