//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceEquipmenttest
    {
        public int SourceEq_id { get; set; }
        public string En_Equipment { get; set; }
        public string De_Equipment { get; set; }
        public string code { get; set; }
        public string codeCompany { get; set; }
    }
}
