//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegistierung
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTab
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Projektname { get; set; }
        public string password { get; set; }
        public Nullable<bool> isAdmin { get; set; }
    }
}
